# NinjaX Server Configuration

# Server settings
server:
  port: 8080
  host: 0.0.0.0
  workers: 1
  auto_restart: true  # Enable auto-restart on configuration changes

# Logging configuration
logging:
  level: info
  access_log: logs/access.log
  error_log: logs/error.log

# HTTP server settings
http:
  static:
    enabled: true
    root: ./public
    options:
      index:
        - index.html
        - index.htm
      extensions:
        - html
        - htm
      fallthrough: true

# Reverse proxy settings
proxy:
  enabled: true
  ws: false  # WebSocket support
  locations:
    # Example API proxy with load balancing
    - path: /api
      # Single target (fallback)
      target: https://jsonplaceholder.typicode.com/posts
      # Multiple targets for load balancing
      targets:
        - https://jsonplaceholder.typicode.com/photos
        - https://jsonplaceholder.typicode.com/todos
        - https://jsonplaceholder.typicode.com/comments
        # - https://dummyjson.com/
        # - https://reqres.in/api/
      # Load balancing configuration
      loadBalancing:
        algorithm: round_robin  # Options: round_robin, least_connections, ip_hash, random
        healthCheck:
          enabled: true
          interval: 10000  # Check every 10 seconds
          path: /
          timeout: 2000
      options:
        changeOrigin: true
        pathRewrite:
          '^/api': ''
        ws: false
    
    # Example static content proxy with load balancing
    - path: /static-content
      target: http://localhost:3000
      # targets:
      #   - http://localhost:3000
      #   - http://localhost:3001
      #   - http://localhost:3002
      # loadBalancing:
      #   algorithm: least_connections
      options:
        changeOrigin: true